package com.jensroggeband.coffeeit.ui.theme

import androidx.compose.ui.graphics.Color

val light_primary = Color(0xFF2f6b26)
val light_onPrimary = Color(0xFFffffff)
val light_primaryContainer = Color(0xFFb0f49e)
val light_onPrimaryContainer = Color(0xFF002200)
val light_secondary = Color(0xFF53634d)
val light_onSecondary = Color(0xFFffffff)
val light_secondaryContainer = Color(0xFFd7e8cd)
val light_onSecondaryContainer = Color(0xFF111f0e)
val light_tertiary = Color(0xFF386568)
val light_onTertiary = Color(0xFFffffff)
val light_tertiaryContainer = Color(0xFFbcebee)
val light_onTertiaryContainer = Color(0xFF002022)
val light_error = Color(0xFFba1b1b)
val light_errorContainer = Color(0xFFffdad4)
val light_onError = Color(0xFFffffff)
val light_onErrorContainer = Color(0xFF410001)
val light_background = Color(0xFFfcfcf6)
val light_onBackground = Color(0xFF1a1c19)
val light_surface = Color(0xFFfcfcf6)
val light_onSurface = Color(0xFF1a1c19)
val light_surfaceVariant = Color(0xFFdfe4d8)
val light_onSurfaceVariant = Color(0xFF43493f)
val light_outline = Color(0xFF73796e)
val light_inverseOnSurface = Color(0xFFf1f1eb)
val light_inverseSurface = Color(0xFF2f312d)
val light_inversePrimary = Color(0xFF95d784)
val light_shadow = Color(0xFF000000)

val dark_primary = Color(0xFF95d784)
val dark_onPrimary = Color(0xFF003a00)
val dark_primaryContainer = Color(0xFF155210)
val dark_onPrimaryContainer = Color(0xFFb0f49e)
val dark_secondary = Color(0xFFbbcbb2)
val dark_onSecondary = Color(0xFF263422)
val dark_secondaryContainer = Color(0xFF3c4b37)
val dark_onSecondaryContainer = Color(0xFFd7e8cd)
val dark_tertiary = Color(0xFFa0cfd2)
val dark_onTertiary = Color(0xFF00373a)
val dark_tertiaryContainer = Color(0xFF1e4d50)
val dark_onTertiaryContainer = Color(0xFFbcebee)
val dark_error = Color(0xFFffb4a9)
val dark_errorContainer = Color(0xFF930006)
val dark_onError = Color(0xFF680003)
val dark_onErrorContainer = Color(0xFFffdad4)
val dark_background = Color(0xFF1a1c19)
val dark_onBackground = Color(0xFFe2e3dc)
val dark_surface = Color(0xFF1a1c19)
val dark_onSurface = Color(0xFFe2e3dc)
val dark_surfaceVariant = Color(0xFF43493f)
val dark_onSurfaceVariant = Color(0xFFc3c9bc)
val dark_outline = Color(0xFF8d9388)
val dark_inverseOnSurface = Color(0xFF1a1c19)
val dark_inverseSurface = Color(0xFFe2e3dc)
val dark_inversePrimary = Color(0xFF2f6b26)
val dark_shadow = Color(0xFF000000)

val seed = Color(0xFFaed7a0)
val error = Color(0xFFba1b1b)